import pytest
from pathlib import Path
from blogger.utils.tools import read_section_tool, save_section_tool, finalize_post_tool, POSTS_DIR

@pytest.fixture
def mock_blog(tmp_path, monkeypatch):
    """Set up a mock blog directory with an organized draft."""
    # Mock POSTS_DIR to use tmp_path
    monkeypatch.setattr("blogger.utils.tools.POSTS_DIR", tmp_path)
    
    blog_id = "test-blog"
    blog_dir = tmp_path / blog_id
    blog_dir.mkdir()
    
    content = """# Test Blog

## Introduction
Intro content here.

## Body Section
Body content here.
More body.

## Conclusion
Conclusion content.
"""
    organized_path = blog_dir / "2-draft_organized.md"
    organized_path.write_text(content)
    
    return blog_id, organized_path

def test_read_section_success(mock_blog):
    blog_id, _ = mock_blog
    
    # Test reading Introduction
    result = read_section_tool(blog_id, "Introduction")
    assert result["status"] == "success"
    assert result["section_heading"] == "Introduction"
    assert "Intro content here." in result["section_content"]
    assert result["prev_section"] is None
    assert result["next_section"] == "Body Section"
    
    # Test reading Body
    result = read_section_tool(blog_id, "Body Section")
    assert result["status"] == "success"
    assert result["section_heading"] == "Body Section"
    assert "Body content here." in result["section_content"]
    assert result["prev_section"] == "Introduction"
    assert result["next_section"] == "Conclusion"

def test_read_section_not_found(mock_blog):
    blog_id, _ = mock_blog
    result = read_section_tool(blog_id, "Non-existent Section")
    assert result["status"] == "error"
    assert "not found" in result["message"]

def test_save_section_success(mock_blog):
    blog_id, organized_path = mock_blog
    
    new_body = "## Body Section\nUpdated body content."
    result = save_section_tool(blog_id, "Body Section", new_body)
    
    assert result["status"] == "success"
    
    # Verify file content
    updated_content = organized_path.read_text()
    assert "Updated body content." in updated_content
    assert "Intro content here." in updated_content  # Intro preserved
    assert "Conclusion content." in updated_content # Conclusion preserved

def test_save_section_validation_fail(mock_blog):
    blog_id, _ = mock_blog
    
    # Missing heading
    result = save_section_tool(blog_id, "Introduction", "Just some text without heading")
    assert result["status"] == "error"
    assert "must include the section heading" in result["message"]
    
    # Mismatched heading
    result = save_section_tool(blog_id, "Introduction", "## Wrong Heading\nContent")
    assert result["status"] == "error"
    assert "does not match target section" in result["message"]

def test_finalize_post_success(mock_blog):
    blog_id, organized_path = mock_blog
    
    result = finalize_post_tool(blog_id)
    assert result["status"] == "success"
    
    final_path = Path(result["final_path"])
    assert final_path.exists()
    assert final_path.name == "3-final.md"
    
    final_content = final_path.read_text()
    assert "Intro content here." in final_content
    assert "*Generated by AI Blog Partner on" in final_content
